import type { ContextualFeatureGuide } from "./context";

const guide = (
  id: string,
  title: string,
  ...routes: string[]
): ContextualFeatureGuide => ({ id, title, routes });

export const CONTEXTUAL_FEATURE_GUIDES: ContextualFeatureGuide[] = [
  guide("shell-home", "Intra home", "/"),
  guide("sign-in", "Sign in", "/login"),
  guide("reset-password", "Password reset", "/reset-password"),
  guide("knowledge-library", "Knowledge Base", "/knowledge"),
  guide("offline-status", "Offline status", "/~offline"),
  guide("my-work", "My Work", "/work"),
  guide("events-workspace", "Events workspace", "/events"),
  guide("insights-workspace", "Insights workspace", "/insights"),
  guide("product-governance", "Product readiness and go-live", "/product"),
  guide("admin-governance", "Administration governance", "/admin"),
  guide("admin-users", "User and role administration", "/admin/users"),
  guide("admin-audit", "Administration audit trail", "/admin/audit"),
  guide("admin-departments", "Department administration", "/admin/departments"),
  guide("admin-doa", "Delegation of Authority administration", "/admin/doa"),
  guide("warehouse-dashboard", "Warehouse dashboard", "/warehouse"),
  guide("warehouse-scan", "Warehouse scan", "/warehouse/scan"),
  guide("warehouse-tasks", "Warehouse tasks", "/warehouse/tasks"),
  guide("warehouse-inventory", "Inventory browser", "/warehouse/inventory"),
  guide(
    "warehouse-product-detail",
    "Warehouse product detail",
    "/warehouse/inventory/:id",
  ),
  guide("warehouse-receiving", "Warehouse receiving", "/warehouse/receiving"),
  guide("warehouse-allocations", "Stock allocations", "/warehouse/allocations"),
  guide(
    "warehouse-fulfillment",
    "Cross-department fulfillment",
    "/warehouse/fulfillment",
  ),
  guide("warehouse-returns", "Warehouse returns", "/warehouse/returns"),
  guide(
    "warehouse-storage",
    "Warehouse storage areas and bins",
    "/warehouse/storage",
  ),
  guide("warehouse-events", "Warehouse events", "/warehouse/events"),
  guide(
    "warehouse-event-detail",
    "Warehouse event detail",
    "/warehouse/events/:id",
  ),
  guide(
    "warehouse-procurement-planning",
    "Warehouse procurement planning",
    "/warehouse/procurement",
  ),
  guide(
    "warehouse-purchase-orders",
    "Warehouse purchase orders",
    "/warehouse/purchase-orders",
  ),
  guide("warehouse-cycle-counts", "Cycle counts", "/warehouse/cycle-counts"),
  guide("warehouse-quality", "Quality control", "/warehouse/quality"),
  guide("warehouse-approvals", "Stock approvals", "/warehouse/approvals"),
  guide(
    "warehouse-exceptions",
    "Warehouse exceptions",
    "/warehouse/exceptions",
  ),
  guide("warehouse-finance", "Finance control center", "/finance"),
  guide("warehouse-pricing", "Warehouse pricing", "/warehouse/pricing"),
  guide("warehouse-data", "Warehouse data and analytics", "/warehouse/data"),
  guide("warehouse-reports", "Inventory reports", "/warehouse/reports"),
  guide("warehouse-suppliers", "Warehouse suppliers", "/warehouse/suppliers"),
  guide("warehouse-locations", "Warehouse locations", "/warehouse/locations"),
  guide("warehouse-imports", "Warehouse imports", "/warehouse/imports"),
  guide(
    "warehouse-operation-routes",
    "Warehouse operation routes",
    "/warehouse/operation-routes",
  ),
  guide("procurement-requests", "Purchase requests", "/procurement"),
  guide(
    "procurement-request-create",
    "Create purchase request",
    "/procurement/requests/new",
  ),
  guide(
    "procurement-request-detail",
    "Purchase request detail",
    "/procurement/requests/:id",
  ),
  guide(
    "procurement-approvals",
    "Procurement approval inbox",
    "/procurement/approvals",
  ),
  guide(
    "procurement-purchase-orders",
    "Procurement purchase orders",
    "/procurement/purchase-orders",
  ),
  guide(
    "procurement-po-detail",
    "Purchase order detail",
    "/procurement/purchase-orders/:id",
  ),
  guide("legal-cases", "Legal accreditation cases", "/legal"),
  guide(
    "legal-case-detail",
    "Legal accreditation case detail",
    "/legal/cases/:id",
  ),
  guide(
    "legal-case-application",
    "Legal vendor application review",
    "/legal/cases/:id/application",
  ),
  guide(
    "legal-sign-instrument",
    "Legal instrument signature",
    "/legal/cases/:id/sign/:code",
  ),
  guide("legal-invite-vendor", "Invite vendor", "/legal/invites/new"),
  guide("vendor-cases", "Vendor portal cases", "/vendor"),
  guide("vendor-case-detail", "Vendor portal case detail", "/vendor/cases/:id"),
  guide(
    "vendor-application",
    "Vendor application",
    "/vendor/cases/:id/application",
  ),
  guide(
    "vendor-sign-instrument",
    "Vendor instrument signature",
    "/vendor/cases/:id/sign/:code",
  ),
  guide(
    "vendor-invite-unavailable",
    "Vendor invite route protection",
    "/vendor/invites/new",
  ),
];
