'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { Badge, Icon, money, useToast } from '@intra/ui';
import { MWELL_OPERATING_PROFILE } from '../policyProfile';
import { evaluateSourcingReadiness } from '../policy';
import { BestValueEvaluation } from './BestValueEvaluation';
import type { AwardRecommendation, CommercialTabulation, FailedBidReason, ProcurementPolicyControls, ProcurementVendor, RecommendationVarianceDecision, SourcingEventStatus, SourcingMethod, TechnicalEvaluation, VarianceReviewEligibility } from '../types';

interface RpcClient { schema(name: string): { rpc(name: string, args: { payload: Record<string, unknown> }): PromiseLike<{ data: unknown; error: { message: string } | null }> } }
interface SourcingResponse { id: string; vendorId: string; vendorName: string; accredited?: boolean; invitedAt?: string; receivedAt?: string; deadlineCompliant?: boolean; proposalReference?: string; commercial?: { amount?: number }; technical?: { score?: number } }
interface Communication { id: string; communicationType: 'invitation' | 'clarification' | 'extension' | 'requote' | 'award_notice' | 'failed_bid_notice'; notificationGroupId?: string; packageVersion?: string; packageHash?: string; sentAt?: string; deliveredAt?: string; acknowledgedAt?: string; acknowledgementState?: 'pending' | 'overdue' | 'acknowledged' | 'superseded'; clarificationState?: 'pending' | 'overdue' | 'answered' }
interface SourcingEvent { id: string; status: SourcingEventStatus; submissionDeadline?: string; intendedResponses?: number; packageVersion?: string; packageHash?: string; failedBidReason?: FailedBidReason; selectedVendorId?: string; closureNote?: string; responses: SourcingResponse[]; communications?: Communication[]; policyControls?: ProcurementPolicyControls; policyControlSources?: Partial<Record<keyof ProcurementPolicyControls, string>>; commercialTabulations?: CommercialTabulation[]; technicalEvaluations?: TechnicalEvaluation[]; awardRecommendation?: AwardRecommendation | null; varianceDecisions?: RecommendationVarianceDecision[]; varianceEligibility?: VarianceReviewEligibility }
interface BidException { id: string; status: 'under_review' | 'approved' | 'rejected'; justification: string; price_reasonableness?: string }

const failedBidOptions: Array<{ value: FailedBidReason; label: string }> = [
  { value: 'insufficient_responses', label: 'Insufficient usable responses' },
  { value: 'non_compliant_submissions', label: 'Submissions are non-compliant' },
  { value: 'all_technically_non_compliant', label: 'All submissions failed technical evaluation' },
  { value: 'implausible_pricing', label: 'Pricing is implausible' },
];

function statusTone(status: SourcingEventStatus | undefined) {
  if (status === 'awarded') return 'emerald' as const;
  if (status === 'failed_bid') return 'rose' as const;
  if (status === 'issued' || status === 'response_closed' || status === 'evaluation') return 'cyan' as const;
  return 'slate' as const;
}

export function SourcingWorkspace({ requestId, method, canManage, canApprove, client, vendors, onChanged }: {
  requestId: string; method: SourcingMethod; canManage: boolean; canApprove: boolean; client: RpcClient | null; vendors: ProcurementVendor[]; onChanged?: () => Promise<void>;
}) {
  const { success, error } = useToast();
  const [event, setEvent] = useState<SourcingEvent | null>(null);
  const [bidException, setBidException] = useState<BidException | null>(null);
  const [loading, setLoading] = useState(Boolean(client));
  const [busy, setBusy] = useState(false);
  const [deadline, setDeadline] = useState('');
  const [invitationTarget, setInvitationTarget] = useState(3);
  const [packageVersion, setPackageVersion] = useState('');
  const [packageHash, setPackageHash] = useState('');
  const [vendorId, setVendorId] = useState('');
  const [proposalReference, setProposalReference] = useState('');
  const [quotedAmount, setQuotedAmount] = useState(0);
  const [technicalScore, setTechnicalScore] = useState(0);
  const [failedBidReason, setFailedBidReason] = useState<FailedBidReason>('insufficient_responses');
  const [extensionDays, setExtensionDays] = useState(1);
  const [clarificationQuestion, setClarificationQuestion] = useState('');
  const [clarificationAnswer, setClarificationAnswer] = useState('');
  const [exceptionJustification, setExceptionJustification] = useState('');
  const [priceReasonableness, setPriceReasonableness] = useState('');
  const [exceptionReviewNote, setExceptionReviewNote] = useState('');

  const call = useCallback(async (name: string, payload: Record<string, unknown>) => {
    if (!client) throw new Error('The governed sourcing workspace requires the live database.');
    const { data, error: rpcError } = await client.schema('procurement').rpc(name, { payload });
    if (rpcError) throw new Error(rpcError.message);
    return data;
  }, [client]);
  const load = useCallback(async () => {
    if (!client) { setLoading(false); return; }
    setLoading(true);
    try {
      const [data, exception, evaluation] = await Promise.all([
        call('sourcing_workspace', { request_id: requestId }) as Promise<{ event?: SourcingEvent | null }>,
        call('insufficient_bid_exception', { request_id: requestId }) as Promise<BidException | null>,
        call('evaluation_workspace', { request_id: requestId }) as Promise<Pick<SourcingEvent, 'commercialTabulations' | 'technicalEvaluations' | 'awardRecommendation' | 'varianceDecisions'>>,
      ]);
      const next = data.event ? { ...data.event, ...evaluation } : null;
      setEvent(next); setBidException(exception);
      if (next?.submissionDeadline) setDeadline(next.submissionDeadline.slice(0, 16));
      if (next?.intendedResponses) setInvitationTarget(next.intendedResponses);
      if (next?.packageVersion) setPackageVersion(next.packageVersion);
      if (next?.packageHash) setPackageHash(next.packageHash);
      if (next?.failedBidReason) setFailedBidReason(next.failedBidReason);
    } catch (cause) { error(cause instanceof Error ? cause.message : 'Could not load sourcing.'); } finally { setLoading(false); }
  }, [call, client, error, requestId]);
  useEffect(() => { void load(); }, [load]);

  const controls = event?.policyControls ?? MWELL_OPERATING_PROFILE.controls;
  const controlSources = event?.policyControlSources ?? MWELL_OPERATING_PROFILE.controlSources;
  const received = useMemo(() => event?.responses.filter((item) => item.receivedAt) ?? [], [event]);
  const accreditedInvites = useMemo(() => event?.responses.filter((item) => item.accredited !== false).length ?? 0, [event]);
  const readiness = evaluateSourcingReadiness({ method, invited: accreditedInvites, usableResponses: received.length, failedBidReason: event?.failedBidReason, exceptionApproved: bidException?.status === 'approved', profile: { ...MWELL_OPERATING_PROFILE, controls } });
  const invitedVendorIds = useMemo(() => new Set(event?.responses.map((item) => item.vendorId) ?? []), [event]);
  const availableVendors = vendors.filter((item) => !invitedVendorIds.has(item.id));
  const canInvite = event?.status === 'draft' || event?.status === 'failed_bid';
  const canOpenEvaluation = event?.status === 'response_closed' || (event?.status === 'failed_bid' && bidException?.status === 'approved');
  const canEvaluate = event?.status === 'evaluation';
  const issueReady = accreditedInvites >= controls.inviteTargetMin;

  async function run(action: () => Promise<void>, message: string) {
    setBusy(true);
    try { await action(); await load(); await onChanged?.(); success(message); }
    catch (cause) { error(cause instanceof Error ? cause.message : 'Could not update sourcing.'); }
    finally { setBusy(false); }
  }
  const saveEvent = () => run(() => call('save_sourcing_event', { request_id: requestId, submission_deadline: deadline ? new Date(deadline).toISOString() : null, intended_responses: invitationTarget, package_version: packageVersion.trim(), package_hash: packageHash.trim() }).then(() => undefined), event ? 'Sourcing plan updated' : 'Sourcing plan created');
  const inviteVendor = () => event && vendorId ? (event.status === 'failed_bid'
    ? run(() => call('transition_sourcing_event', { id: event.id, action: 'source_additional_and_requote', vendor_id: vendorId, submission_deadline: deadline ? new Date(deadline).toISOString() : null, package_version: packageVersion.trim(), package_hash: packageHash.trim() }).then(() => undefined), 'Additional vendor sourced and equal requote issued')
    : run(() => call('invite_sourcing_vendors', { sourcing_event_id: event.id, vendor_ids: [vendorId] }).then(() => undefined), 'Controlled vendor invitation recorded')
  ).finally(() => setVendorId('')) : undefined;
  const recordResponse = () => event && vendorId ? run(() => call('record_sourcing_response', { sourcing_event_id: event.id, vendor_id: vendorId, received_at: new Date().toISOString(), proposal_storage_path: proposalReference.trim(), commercial: { amount: quotedAmount }, technical: { score: technicalScore } }).then(() => undefined), 'Vendor response recorded').finally(() => { setVendorId(''); setProposalReference(''); setQuotedAmount(0); setTechnicalScore(0); }) : undefined;
  const transition = (action: string, message: string, extra: Record<string, unknown> = {}) => event && run(() => call('transition_sourcing_event', { id: event.id, action, ...extra }).then(() => undefined), message);
  const communicate = (communicationType: 'clarification' | 'extension') => event && run(() => call('record_solicitation_communication', communicationType === 'clarification' ? { sourcing_event_id: event.id, communication_type: 'clarification', question: clarificationQuestion.trim(), answer: clarificationAnswer.trim() } : { sourcing_event_id: event.id, communication_type: 'extension', extension_calendar_days: extensionDays }).then(() => undefined), communicationType === 'clarification' ? 'Clarification broadcast to every invitee' : 'Deadline extended and every invitee notified').finally(() => { if (communicationType === 'clarification') { setClarificationQuestion(''); setClarificationAnswer(''); } });
  const submitException = () => event && run(() => call('submit_insufficient_bid_exception', { sourcing_event_id: event.id, phase: event.status === 'draft' ? 'pre_issue' : 'evaluation', justification: exceptionJustification.trim(), price_reasonableness: priceReasonableness.trim() }).then(() => undefined), event.status === 'draft' ? 'Pre-issue invitation exception submitted for independent review' : 'Evaluation-with-fewer-than-three exception submitted for independent review').finally(() => { setExceptionJustification(''); setPriceReasonableness(''); });
  const reviewException = (decision: 'approved' | 'rejected') => bidException && run(() => call('review_insufficient_bid_exception', { id: bidException.id, decision, note: exceptionReviewNote.trim() }).then(() => undefined), decision === 'approved' ? 'Sourcing exception approved' : 'Sourcing exception rejected').finally(() => setExceptionReviewNote(''));

  if (loading) return <div className="h-32 animate-pulse rounded-lg bg-inset" aria-busy="true" />;
  return <section className="space-y-4" aria-label="Governed competitive sourcing">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold text-ink">{method.toUpperCase()} competitive sourcing</h2><p className="max-w-2xl text-sm text-muted">Issue one controlled package, capture equal communications, and open only compliant responses. The server owns deadline, quorum, exception, and transition decisions.</p></div><Badge tone={statusTone(event?.status)}>{event?.status?.replaceAll('_', ' ') ?? 'Not started'}</Badge></div>
    {!client && <p className="rounded-lg border border-amber-500/30 bg-amber-500/5 p-3 text-sm text-ink">Connect to the live database to operate governed sourcing.</p>}
    {canManage && (!event || event.status === 'draft') && <section className="grid gap-3 border-t border-line pt-4 lg:grid-cols-[minmax(15rem,1fr)_10rem_12rem_auto] lg:items-end"><label className="block text-sm font-semibold text-ink">Submission deadline<input aria-label="Submission deadline" type="datetime-local" className="input mt-1.5" value={deadline} onChange={(e) => setDeadline(e.target.value)} /></label><label className="block text-sm font-semibold text-ink">Invite target<select aria-label="Invite target" className="input mt-1.5" value={invitationTarget} onChange={(e) => setInvitationTarget(Number(e.target.value))}><option value={3}>3 vendors</option><option value={4}>4 vendors</option></select></label><label className="block text-sm font-semibold text-ink">Package version<input aria-label="Package version" className="input mt-1.5" value={packageVersion} onChange={(e) => setPackageVersion(e.target.value)} placeholder="RFQ-2026.08-v1" /></label><button type="button" className="btn-primary min-h-11 w-full lg:w-auto" disabled={busy || !deadline || !packageVersion.trim() || !packageHash.trim()} onClick={() => void saveEvent()}><Icon name="check" className="h-4 w-4" />{event ? 'Save plan' : 'Create plan'}</button><label className="block text-sm font-semibold text-ink lg:col-span-3">Package SHA-256<input aria-label="Package SHA-256" className="input mt-1.5" value={packageHash} onChange={(e) => setPackageHash(e.target.value)} placeholder="Evidence digest" /></label><p className="text-xs text-muted lg:col-span-1">Issue requires {controls.inviteTargetMin} accredited invitees and at least {controls.bidWindowWorkingDays} working days. Source: {controlSources.inviteTargetMin ?? controlSources.bidWindowWorkingDays ?? 'request-bound policy profile'}.</p></section>}
    {event && <>
      <dl className="grid grid-cols-2 gap-3 rounded-lg border border-line bg-inset p-3 text-sm sm:grid-cols-4"><div><dt className="text-xs text-muted">Accredited invitees</dt><dd className="font-semibold text-ink">{accreditedInvites}</dd></div><div><dt className="text-xs text-muted">Usable responses</dt><dd className="font-semibold text-ink">{received.length}</dd></div><div><dt className="text-xs text-muted">Target</dt><dd className="font-semibold text-ink">{event.intendedResponses ?? 3}</dd></div><div><dt className="text-xs text-muted">Deadline</dt><dd className="font-semibold text-ink">{event.submissionDeadline ? new Date(event.submissionDeadline).toLocaleString() : 'Not set'}</dd></div></dl>
      {event.responses.length > 0 && <div className="overflow-x-auto rounded-lg border border-line"><table className="min-w-[42rem] w-full text-left text-sm"><thead className="bg-inset text-xs text-muted"><tr><th className="px-3 py-2">Vendor</th><th className="px-3 py-2">Accreditation</th><th className="px-3 py-2">Response</th><th className="px-3 py-2">Quote</th><th className="px-3 py-2">Technical</th></tr></thead><tbody className="divide-y divide-line">{event.responses.map((response) => <tr key={response.id}><td className="px-3 py-3 font-medium text-ink">{response.vendorName}</td><td className="px-3 py-3"><Badge tone={response.accredited === false ? 'rose' : 'emerald'}>{response.accredited === false ? 'Not accredited' : 'Accredited'}</Badge></td><td className="px-3 py-3"><Badge tone={response.receivedAt ? response.deadlineCompliant === false ? 'amber' : 'emerald' : 'slate'}>{response.receivedAt ? response.deadlineCompliant === false ? 'Late' : 'Received' : 'Invited'}</Badge></td><td className="px-3 py-3 text-ink">{response.commercial?.amount ? money(response.commercial.amount) : 'Pending'}</td><td className="px-3 py-3 text-ink">{response.technical?.score ?? 'Pending'}</td></tr>)}</tbody></table></div>}
      {canManage && canInvite && <section className="space-y-3 rounded-lg border border-line p-3"><p className="text-sm text-muted">{event.status === 'failed_bid' ? 'Source one additional accredited vendor, version the package, and send the same requote notice to every invitee.' : 'Invite accredited vendors to the controlled package.'}</p>{event.status === 'failed_bid' && <div className="grid gap-3 md:grid-cols-3"><label className="block text-sm font-semibold text-ink">Requote deadline<input aria-label="Requote deadline" type="datetime-local" className="input mt-1.5" value={deadline} onChange={(e) => setDeadline(e.target.value)} /></label><label className="block text-sm font-semibold text-ink">Requote package version<input aria-label="Requote package version" className="input mt-1.5" value={packageVersion} onChange={(e) => setPackageVersion(e.target.value)} /></label><label className="block text-sm font-semibold text-ink">Requote package SHA-256<input aria-label="Requote package SHA-256" className="input mt-1.5" value={packageHash} onChange={(e) => setPackageHash(e.target.value)} /></label></div>}<div className="grid gap-2 sm:grid-cols-[1fr_auto]"><select aria-label="Vendor to invite" className="input" value={vendorId} onChange={(e) => setVendorId(e.target.value)}><option value="">Select accredited vendor to invite</option>{availableVendors.map((vendor) => <option key={vendor.id} value={vendor.id}>{vendor.legalName}</option>)}</select><button type="button" className="btn-outline min-h-11 w-full sm:w-auto" disabled={busy || !vendorId || (event.status === 'failed_bid' && (!deadline || !packageVersion.trim() || !packageHash.trim()))} onClick={() => void inviteVendor()}><Icon name="plus" className="h-4 w-4" />{event.status === 'failed_bid' ? 'Source and requote' : 'Record invitation'}</button></div></section>}
      {canManage && event.status === 'draft' && <><button type="button" className="btn-primary min-h-11 w-full sm:w-auto" disabled={busy || !issueReady} onClick={() => void transition('issue', 'Sourcing event issued to every invited vendor')}><Icon name="arrowRight" className="h-4 w-4" />Issue controlled package</button>{!issueReady && <section className="space-y-3 rounded-lg border border-amber-500/30 bg-amber-500/5 p-3 text-sm text-ink"><p>At least {controls.inviteTargetMin} accredited invitees are required before issue. Submit a pre-issue exception only when the documented vendor search cannot meet that minimum.</p>{(!bidException || bidException.status === 'rejected') && <div className="grid gap-3 md:grid-cols-2"><label className="block text-sm font-semibold text-ink md:col-span-2">Why issue may proceed<textarea className="input mt-1.5" rows={3} value={exceptionJustification} onChange={(e) => setExceptionJustification(e.target.value)} /></label><label className="block text-sm font-semibold text-ink md:col-span-2">Price reasonableness evidence<textarea className="input mt-1.5" rows={2} value={priceReasonableness} onChange={(e) => setPriceReasonableness(e.target.value)} /></label><button type="button" className="btn-outline min-h-11 w-full md:w-auto" disabled={busy || exceptionJustification.trim().length < 20 || priceReasonableness.trim().length < 10} onClick={() => void submitException()}><Icon name="arrowRight" className="h-4 w-4" />Submit pre-issue exception</button></div>}</section>}</>}
      {canManage && event.status === 'issued' && <section className="grid gap-3 rounded-lg bg-inset p-3 md:grid-cols-2"><label className="block text-sm font-semibold text-ink">Invited vendor<select aria-label="Invited vendor" className="input mt-1.5" value={vendorId} onChange={(e) => setVendorId(e.target.value)}><option value="">Select invited vendor</option>{event.responses.filter((response) => !response.receivedAt).map((response) => <option key={response.vendorId} value={response.vendorId}>{response.vendorName}</option>)}</select></label><label className="block text-sm font-semibold text-ink">Proposal evidence reference<input aria-label="Proposal evidence reference" className="input mt-1.5" value={proposalReference} onChange={(e) => setProposalReference(e.target.value)} /></label><label className="block text-sm font-semibold text-ink">Quoted amount<input aria-label="Quoted amount" type="number" min={0} step="0.01" className="input mt-1.5" value={quotedAmount} onChange={(e) => setQuotedAmount(Math.max(0, Number(e.target.value) || 0))} /></label><label className="block text-sm font-semibold text-ink">Technical score (0-100)<input aria-label="Technical score (0-100)" type="number" min={0} max={100} className="input mt-1.5" value={technicalScore} onChange={(e) => setTechnicalScore(Math.min(100, Math.max(0, Number(e.target.value) || 0)))} /></label><button type="button" className="btn-primary min-h-11 w-full md:col-span-2 md:w-auto" disabled={busy || !vendorId || !proposalReference.trim() || quotedAmount <= 0} onClick={() => void recordResponse()}><Icon name="check" className="h-4 w-4" />Record response</button></section>}
      {canManage && event.status === 'issued' && <div className="flex flex-wrap gap-2"><button type="button" className="btn-outline min-h-11" disabled={busy} onClick={() => void transition('response_closed', 'Response window closed for controlled opening')}><Icon name="check" className="h-4 w-4" />Close response window</button><button type="button" className="btn-outline min-h-11" disabled={busy} onClick={() => void transition('failed_bid', 'Failed-bid recovery opened', { failed_bid_reason: failedBidReason })}><Icon name="alert" className="h-4 w-4" />Mark failed bid</button><select aria-label="Failed bid reason" className="input min-h-11" value={failedBidReason} onChange={(e) => setFailedBidReason(e.target.value as FailedBidReason)}>{failedBidOptions.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></div>}
      {canManage && (event.status === 'issued' || event.status === 'failed_bid') && <section className="grid gap-3 rounded-lg border border-line p-3 md:grid-cols-[1fr_auto]"><label className="block text-sm font-semibold text-ink">Extend deadline (calendar days)<input aria-label="Extension calendar days" type="number" min={1} max={controls.maxExtensionCalendarDays} className="input mt-1.5" value={extensionDays} onChange={(e) => setExtensionDays(Math.min(controls.maxExtensionCalendarDays, Math.max(1, Number(e.target.value) || 1)))} /></label><button type="button" className="btn-outline min-h-11 w-full md:w-auto" disabled={busy || extensionDays > controls.maxExtensionCalendarDays} onClick={() => void communicate('extension')}><Icon name="arrowRight" className="h-4 w-4" />Extend and notify all</button><p className="text-xs text-muted md:col-span-2">An extension is limited to {controls.maxExtensionCalendarDays} calendar days and sends the same notice to every invitee. Source: {controlSources.maxExtensionCalendarDays ?? 'request-bound policy profile'}.</p></section>}
      {canManage && (event.status === 'issued' || event.status === 'response_closed' || event.status === 'evaluation') && <section className="grid gap-3 rounded-lg border border-line p-3 md:grid-cols-2"><label className="block text-sm font-semibold text-ink">Clarification question<textarea aria-label="Clarification question" className="input mt-1.5" rows={2} value={clarificationQuestion} onChange={(e) => setClarificationQuestion(e.target.value)} /></label><label className="block text-sm font-semibold text-ink">Approved answer<textarea aria-label="Approved answer" className="input mt-1.5" rows={2} value={clarificationAnswer} onChange={(e) => setClarificationAnswer(e.target.value)} /></label><button type="button" className="btn-outline min-h-11 w-full md:w-auto" disabled={busy || !clarificationQuestion.trim() || !clarificationAnswer.trim()} onClick={() => void communicate('clarification')}><Icon name="arrowRight" className="h-4 w-4" />Broadcast identical clarification</button></section>}
      {event.status === 'failed_bid' && <section className="space-y-3 rounded-lg border border-rose-500/30 bg-rose-500/5 p-3"><div><p className="font-semibold text-ink">Failed-bid recovery</p><p className="text-sm text-muted">Reason: {failedBidOptions.find((item) => item.value === event.failedBidReason)?.label ?? 'Not recorded'}. Requote, extend, or submit an independently reviewed evaluation exception.</p></div>{canManage && (!bidException || bidException.status === 'rejected') && <div className="grid gap-3 md:grid-cols-2"><label className="block text-sm font-semibold text-ink md:col-span-2">Why evaluation may proceed<textarea className="input mt-1.5" rows={3} value={exceptionJustification} onChange={(e) => setExceptionJustification(e.target.value)} /></label><label className="block text-sm font-semibold text-ink md:col-span-2">Price reasonableness evidence<textarea className="input mt-1.5" rows={2} value={priceReasonableness} onChange={(e) => setPriceReasonableness(e.target.value)} /></label><button type="button" className="btn-outline min-h-11 w-full md:w-auto" disabled={busy || exceptionJustification.trim().length < 20 || priceReasonableness.trim().length < 10} onClick={() => void submitException()}><Icon name="arrowRight" className="h-4 w-4" />Submit evaluation exception</button></div>}{canApprove && bidException?.status === 'under_review' && <div className="space-y-3 border-t border-rose-500/20 pt-3"><p className="text-sm text-ink">{bidException.justification}</p><label className="block text-sm font-semibold text-ink">Independent review note<textarea className="input mt-1.5" rows={2} value={exceptionReviewNote} onChange={(e) => setExceptionReviewNote(e.target.value)} /></label><div className="flex flex-wrap gap-2"><button type="button" className="btn-outline min-h-11" disabled={busy || !exceptionReviewNote.trim()} onClick={() => void reviewException('rejected')}>Reject exception</button><button type="button" className="btn-primary min-h-11" disabled={busy || !exceptionReviewNote.trim()} onClick={() => void reviewException('approved')}><Icon name="check" className="h-4 w-4" />Approve exception</button></div></div>}</section>}
      {canManage && canOpenEvaluation && <section className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-cyan-500/30 bg-cyan-500/5 p-3"><div><p className="font-semibold text-ink">Controlled opening ready</p><p className="text-sm text-muted">Open evaluation only after the response evidence and any approved exception are complete.</p></div><button type="button" className="btn-primary min-h-11 w-full sm:w-auto" disabled={busy || !readiness.ready} onClick={() => void transition('evaluation', 'Controlled evaluation opened')}><Icon name="arrowRight" className="h-4 w-4" />Open controlled evaluation</button></section>}
      {canEvaluate && <BestValueEvaluation requestId={requestId} event={event} canManage={canManage} client={client} onChanged={async () => { await load(); await onChanged?.(); }} />}
      {canEvaluate && event.awardRecommendation?.status === 'approved' && <section className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-emerald-500/30 bg-emerald-500/5 p-3"><div><p className="font-semibold text-ink">Approved best-value recommendation</p><p className="text-sm text-muted">Record the final award as a separate controlled transition. The evaluated score and recommendation did not award this vendor by themselves.</p></div><button type="button" className="btn-primary min-h-11 w-full sm:w-auto" disabled={busy || !readiness.ready} onClick={() => void transition('award', 'Sourcing award recorded', { selected_vendor_id: event.awardRecommendation?.recommendedVendorId, closure_note: event.awardRecommendation?.rationale })}><Icon name="check" className="h-4 w-4" />Record controlled award</button></section>}
      {event.communications && event.communications.length > 0 && <section className="rounded-lg border border-line p-3"><h3 className="font-semibold text-ink">Equal communication evidence</h3><p className="mt-1 text-xs text-muted">Acknowledgement status applies only to the vendor&apos;s current invitation or requote package. Earlier packages remain as immutable history.</p><ul className="mt-2 space-y-2 text-sm">{event.communications.map((item) => <li key={item.id} className="flex flex-wrap items-center justify-between gap-2 border-t border-line pt-2 first:border-0 first:pt-0"><span className="min-w-0 text-ink"><span className="block">{item.communicationType.replaceAll('_', ' ')} {item.notificationGroupId ? `· ${item.notificationGroupId}` : ''}</span>{item.packageVersion && <span className="block text-xs text-muted">{item.packageVersion}{item.packageHash ? ` · ${item.packageHash.slice(0, 12)}...` : ''}</span>}</span><span className="text-xs text-muted">{item.acknowledgementState === 'overdue' ? 'Acknowledgment overdue' : item.acknowledgementState === 'superseded' ? 'Superseded package' : item.clarificationState === 'overdue' ? 'Clarification overdue' : item.acknowledgedAt ? 'Acknowledged' : item.deliveredAt ? 'Delivered' : 'Sent'}</span></li>)}</ul></section>}
      {canManage && !['awarded', 'cancelled'].includes(event.status) && <button type="button" className="btn-outline min-h-11" disabled={busy} onClick={() => void transition('cancel', 'Sourcing event cancelled', { closure_note: 'Cancelled by Procurement' })}><Icon name="x" className="h-4 w-4" />Cancel event</button>}
    </>}
  </section>;
}
