// modules/legal/src/requirements/catalog.ts
//
// The mWell vendor-accreditation requirement catalog. Every row is a
// jurisdiction- + entity- + risk- + category-aware definition of a document
// (or a signable instrument) the vendor is expected to hand over during
// accreditation. `requirements/policy.ts` filters this list into the tailored
// checklist a given case actually sees.
//
// Source anchors:
//  - mWell Procurement Policy & Procedures Annex B (PH vendor accreditation)
//  - Real-world PH vendor onboarding (SEC / DTI / BIR / DOLE / FDA / DENR /
//    PhilGEPS / SSS / PhilHealth / Pag-IBIG / NPC / PCAB / LGU)
//  - IRS Form W-9 / W-8BEN-E, US Secretary of State certifications
//  - EU / UK — VAT, Companies House, GDPR DPA, ISO 27001, Modern Slavery Act
//  - APAC — ACRA BizFile (SG), HK BR + CR filings
//  - International — Apostille, Tax Residency, FATF EDD, OFAC / EU / UN
//    sanctions declarations, FCPA / UK Bribery Act
//
// When adding a new row: pick a stable `code`, group it, restrict jurisdictions
// / entityTypes / categories / riskTiers to the values that trigger it, and
// leave `'*'` for "applies everywhere". See docs/VENDOR-ACCREDITATION.md for
// the full checklist of style rules.

import type {
  InstrumentCode,
  RequirementDefinition,
  SpendBand,
} from '../types';

// ---------------------------------------------------------------------------
// PH — Statutory registration
// ---------------------------------------------------------------------------
const PH_STATUTORY: readonly RequirementDefinition[] = [
  {
    code: 'PH_SEC_REG',
    label: 'SEC Certificate of Registration',
    description: 'Latest SEC Certificate of Registration for the corporation or partnership.',
    whyWeNeedIt:
      'Establishes legal personality with the Securities and Exchange Commission — mandatory for every PH corporate vendor.',
    authority: 'SEC',
    helpUrl: 'https://www.sec.gov.ph/',
    jurisdictions: ['PH'],
    entityTypes: ['corporation', 'partnership', 'cooperative', 'branch_foreign'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    evidenceFormat: 'pdf',
    group: 'statutory',
    instrument: false,
    tags: ['ph-mandatory', 'registration'],
  },
  {
    code: 'PH_DTI_REG',
    label: 'DTI Business Name Registration',
    description: 'DTI Business Name Registration certificate for sole proprietors.',
    whyWeNeedIt:
      'The DTI cert is the sole-proprietor equivalent of the SEC registration; without it we can\u2019t transact.',
    authority: 'DTI',
    helpUrl: 'https://bnrs.dti.gov.ph/',
    jurisdictions: ['PH'],
    entityTypes: ['sole_prop'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    renewsAfterMonths: 60,
    evidenceFormat: 'pdf',
    group: 'statutory',
    instrument: false,
    tags: ['ph-mandatory', 'registration'],
  },
  {
    code: 'PH_ARTICLES_INC',
    label: 'Articles of Incorporation & Amendments',
    description: 'Articles of Incorporation, plus every SEC-filed amendment on record.',
    whyWeNeedIt: 'Confirms corporate purpose, capital, and authorized signatories.',
    authority: 'SEC',
    jurisdictions: ['PH'],
    entityTypes: ['corporation', 'cooperative'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    evidenceFormat: 'pdf',
    group: 'statutory',
    instrument: false,
    tags: ['registration'],
  },
  {
    code: 'PH_BYLAWS',
    label: 'Corporate By-Laws',
    description: 'Latest SEC-filed corporate by-laws.',
    whyWeNeedIt: 'Defines how the vendor governs itself and who is authorized to bind it.',
    authority: 'SEC',
    jurisdictions: ['PH'],
    entityTypes: ['corporation'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    evidenceFormat: 'pdf',
    group: 'statutory',
    instrument: false,
  },
  {
    code: 'PH_GIS',
    label: 'General Information Sheet (latest)',
    description: 'General Information Sheet (GIS) filed with SEC for the current year.',
    whyWeNeedIt:
      'Latest snapshot of directors, officers, and shareholding — confirms who signs and who benefits.',
    authority: 'SEC',
    jurisdictions: ['PH'],
    entityTypes: ['corporation'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    renewsAfterMonths: 12,
    evidenceFormat: 'pdf',
    group: 'statutory',
    instrument: false,
    tags: ['renewable'],
  },
];

// ---------------------------------------------------------------------------
// PH — Tax / BIR
// ---------------------------------------------------------------------------
const PH_TAX: readonly RequirementDefinition[] = [
  {
    code: 'PH_BIR_2303',
    label: 'BIR Form 2303 (Certificate of Registration)',
    description: 'BIR Form 2303 — the certificate of registration issued to every taxpayer.',
    whyWeNeedIt:
      'Confirms TIN, RDO, and registered tax type; drives whether we withhold and issue 2307.',
    authority: 'BIR',
    helpUrl: 'https://www.bir.gov.ph/',
    jurisdictions: ['PH'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    evidenceFormat: 'pdf',
    group: 'tax',
    instrument: false,
    tags: ['ph-mandatory'],
  },
  {
    code: 'PH_BIR_0605',
    label: 'BIR Form 0605 — Annual Registration Fee',
    description:
      'Latest BIR Form 0605 payment (Annual Registration Fee) with the machine-validated receipt.',
    whyWeNeedIt: 'Proof the vendor is current with BIR annual registration.',
    authority: 'BIR',
    jurisdictions: ['PH'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    renewsAfterMonths: 12,
    evidenceFormat: 'pdf',
    group: 'tax',
    instrument: false,
    tags: ['renewable'],
  },
  {
    code: 'PH_BIR_2307_SAMPLE',
    label: 'BIR Form 2307 issuance capability (sample)',
    description:
      'Sample BIR 2307 issued by the vendor OR written confirmation of ability to receive withholding.',
    whyWeNeedIt:
      'Confirms the vendor knows their withholding tax mechanics before we start deducting on payables.',
    authority: 'BIR',
    jurisdictions: ['PH'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: false,
    evidenceFormat: 'pdf',
    group: 'tax',
    instrument: false,
  },
  {
    code: 'PH_TAX_CLEARANCE',
    label: 'BIR Tax Clearance / Certificate of Good Standing',
    description: 'BIR Tax Clearance or Certificate of Good Standing valid for the current year.',
    whyWeNeedIt:
      'Assures the vendor is not in tax arrears — required for higher-value engagements and PhilGEPS bids.',
    authority: 'BIR',
    jurisdictions: ['PH'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: false,
    renewsAfterMonths: 12,
    evidenceFormat: 'pdf',
    group: 'tax',
    instrument: false,
    minSpendBand: '1m_10m',
    tags: ['renewable'],
  },
  {
    code: 'PH_SAMPLE_INVOICE',
    label: 'Sample Sales Invoice / Official Receipt',
    description: 'Sample of the vendor\u2019s BIR-registered Sales Invoice or Official Receipt.',
    whyWeNeedIt:
      'Confirms VAT / non-VAT status and the ATP number; AP will not release payment without this.',
    authority: 'BIR',
    jurisdictions: ['PH'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    evidenceFormat: 'img',
    group: 'tax',
    instrument: false,
  },
  {
    code: 'PH_ITR',
    label: 'Latest Income Tax Return (ITR)',
    description: 'Latest filed Income Tax Return with BIR proof of receipt.',
    whyWeNeedIt:
      'For micro / small vendors that don\u2019t issue AFS, the ITR is the primary evidence of financial viability.',
    authority: 'BIR',
    jurisdictions: ['PH'],
    entityTypes: ['sole_prop', 'partnership'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    renewsAfterMonths: 12,
    evidenceFormat: 'pdf',
    group: 'tax',
    instrument: false,
    tags: ['renewable'],
  },
];

// ---------------------------------------------------------------------------
// PH — LGU / regulatory / sector permits
// ---------------------------------------------------------------------------
const PH_REGULATORY: readonly RequirementDefinition[] = [
  {
    code: 'PH_MAYORS_PERMIT',
    label: 'Mayor\u2019s / Business Permit',
    description: 'Current-year Mayor\u2019s or Business Permit issued by the LGU.',
    whyWeNeedIt: 'LGUs require this every year; without it the vendor is not operating legally.',
    authority: 'LGU',
    jurisdictions: ['PH'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    renewsAfterMonths: 12,
    evidenceFormat: 'pdf',
    group: 'regulatory',
    instrument: false,
    tags: ['ph-mandatory', 'renewable'],
  },
  {
    code: 'PH_PHILGEPS',
    label: 'PhilGEPS Registration',
    description: 'Latest PhilGEPS certificate of registration / membership.',
    whyWeNeedIt: 'Required for participation in public-sector-adjacent tenders and referrals.',
    authority: 'PhilGEPS',
    helpUrl: 'https://philgeps.gov.ph/',
    jurisdictions: ['PH'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: false,
    renewsAfterMonths: 12,
    evidenceFormat: 'pdf',
    group: 'regulatory',
    instrument: false,
    tags: ['renewable'],
  },
  {
    code: 'PH_PHILGEPS_PLATINUM',
    label: 'PhilGEPS Platinum Membership',
    description: 'PhilGEPS Platinum-tier membership with the eligibility documents attached.',
    whyWeNeedIt: 'Required for RFP / bid-supported sourcing above the RFP threshold.',
    authority: 'PhilGEPS',
    jurisdictions: ['PH'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['medium', 'high'],
    required: false,
    renewsAfterMonths: 12,
    evidenceFormat: 'pdf',
    group: 'regulatory',
    instrument: false,
    minSpendBand: '1m_10m',
  },
  {
    code: 'PH_SSS_CLEARANCE',
    label: 'SSS Certificate of Good Standing',
    description: 'SSS employer clearance / certificate of good standing.',
    whyWeNeedIt: 'Required for services + manpower vendors so mWell doesn\u2019t inherit unpaid contributions.',
    authority: 'SSS',
    jurisdictions: ['PH'],
    entityTypes: ['*'],
    categories: ['services', 'manpower', 'construction', 'consulting'],
    riskTiers: ['*'],
    required: true,
    renewsAfterMonths: 12,
    evidenceFormat: 'pdf',
    group: 'regulatory',
    instrument: false,
  },
  {
    code: 'PH_PHILHEALTH_CLEARANCE',
    label: 'PhilHealth Employer Clearance',
    description: 'Latest PhilHealth employer clearance.',
    whyWeNeedIt: 'Confirms PhilHealth contributions for vendor employees — required for manpower / services.',
    authority: 'PhilHealth',
    jurisdictions: ['PH'],
    entityTypes: ['*'],
    categories: ['services', 'manpower', 'construction'],
    riskTiers: ['*'],
    required: true,
    renewsAfterMonths: 12,
    evidenceFormat: 'pdf',
    group: 'regulatory',
    instrument: false,
  },
  {
    code: 'PH_PAGIBIG_CLEARANCE',
    label: 'Pag-IBIG Certificate of Coverage',
    description: 'Pag-IBIG certificate of coverage / good standing.',
    whyWeNeedIt: 'Confirms Pag-IBIG remittance current for vendor employees.',
    authority: 'Pag-IBIG',
    jurisdictions: ['PH'],
    entityTypes: ['*'],
    categories: ['services', 'manpower', 'construction'],
    riskTiers: ['*'],
    required: true,
    renewsAfterMonths: 12,
    evidenceFormat: 'pdf',
    group: 'regulatory',
    instrument: false,
  },
  {
    code: 'PH_DOLE_DO_174',
    label: 'DOLE Registration (D.O. 174-17)',
    description: 'DOLE Department Order 174-17 registration for job contractors / manpower suppliers.',
    whyWeNeedIt:
      'D.O. 174-17 registration is legally required to supply manpower under contract — mWell can\u2019t engage otherwise.',
    authority: 'DOLE',
    helpUrl: 'https://bwc.dole.gov.ph/',
    jurisdictions: ['PH'],
    entityTypes: ['*'],
    categories: ['manpower', 'services'],
    riskTiers: ['*'],
    required: true,
    renewsAfterMonths: 36,
    evidenceFormat: 'pdf',
    group: 'regulatory',
    instrument: false,
    contractTypes: ['manpower_supply', 'retainer', 'sla'],
    tags: ['ph-mandatory-manpower'],
  },
  {
    code: 'PH_FDA_LTO',
    label: 'FDA License to Operate',
    description: 'FDA License to Operate (LTO) covering the vendor\u2019s activity.',
    whyWeNeedIt: 'Mandatory to supply medical devices, pharma, or cosmetics into a healthcare distributor.',
    authority: 'FDA',
    helpUrl: 'https://verification.fda.gov.ph/',
    jurisdictions: ['PH'],
    entityTypes: ['*'],
    categories: ['medical_pharma', 'goods'],
    riskTiers: ['*'],
    required: true,
    renewsAfterMonths: 24,
    evidenceFormat: 'pdf',
    group: 'regulatory',
    instrument: false,
    tags: ['ph-mandatory-medical'],
  },
  {
    code: 'PH_FDA_CPR',
    label: 'FDA Certificate of Product Registration',
    description: 'FDA Certificate of Product Registration for each SKU sold to mWell.',
    whyWeNeedIt: 'Every medical / pharma SKU must be individually registered before we can distribute it.',
    authority: 'FDA',
    jurisdictions: ['PH'],
    entityTypes: ['*'],
    categories: ['medical_pharma'],
    riskTiers: ['*'],
    required: true,
    renewsAfterMonths: 60,
    evidenceFormat: 'pdf',
    group: 'regulatory',
    instrument: false,
  },
  {
    code: 'PH_DENR_ECC',
    label: 'DENR Environmental Compliance Certificate',
    description: 'DENR Environmental Compliance Certificate / CNC (Certificate of Non-Coverage).',
    whyWeNeedIt: 'Construction and heavy-goods vendors need a valid ECC before mobilization.',
    authority: 'DENR',
    jurisdictions: ['PH'],
    entityTypes: ['*'],
    categories: ['construction', 'logistics', 'medical_pharma'],
    riskTiers: ['*'],
    required: false,
    evidenceFormat: 'pdf',
    group: 'regulatory',
    instrument: false,
  },
  {
    code: 'PH_DENR_HAZ',
    label: 'DENR Hazardous Waste Transporter Permit',
    description: 'DENR-issued permit to transport / handle hazardous waste (RA 6969).',
    whyWeNeedIt: 'Required for vendors that will move any hazardous material on our behalf.',
    authority: 'DENR',
    jurisdictions: ['PH'],
    entityTypes: ['*'],
    categories: ['logistics', 'construction'],
    riskTiers: ['medium', 'high'],
    required: false,
    renewsAfterMonths: 12,
    evidenceFormat: 'pdf',
    group: 'regulatory',
    instrument: false,
  },
  {
    code: 'PH_PCAB',
    label: 'PCAB License',
    description: 'PCAB (Philippine Contractors Accreditation Board) license current-year.',
    whyWeNeedIt: 'Legally required for any general or specialty construction work.',
    authority: 'PCAB',
    helpUrl: 'https://pcab.dpwh.gov.ph/',
    jurisdictions: ['PH'],
    entityTypes: ['*'],
    categories: ['construction'],
    riskTiers: ['*'],
    required: true,
    renewsAfterMonths: 12,
    evidenceFormat: 'pdf',
    group: 'regulatory',
    instrument: false,
    tags: ['ph-mandatory-construction', 'renewable'],
  },
  {
    code: 'PH_NPC_REG',
    label: 'NPC Registration as PIC / PIP',
    description:
      'National Privacy Commission registration as Personal Information Controller / Processor (RA 10173).',
    whyWeNeedIt:
      'Legally required to process personal data on mWell\u2019s behalf under the PH Data Privacy Act.',
    authority: 'NPC',
    helpUrl: 'https://www.privacy.gov.ph/',
    jurisdictions: ['PH'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    renewsAfterMonths: 12,
    evidenceFormat: 'pdf',
    group: 'regulatory',
    instrument: false,
    requiresPersonalData: true,
    tags: ['data-privacy'],
  },
  {
    code: 'PH_PRIVACY_IMPACT_ASSESSMENT',
    label: 'Privacy Impact Assessment / Data Privacy Compliance Pack',
    description:
      'Privacy Impact Assessment or equivalent Data Privacy Act compliance evidence for the services in scope.',
    whyWeNeedIt:
      'The mWell accreditation form requires privacy-impact and Data Privacy Act evidence when the vendor handles personal data.',
    authority: 'NPC',
    helpUrl: 'https://www.privacy.gov.ph/',
    jurisdictions: ['PH'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    evidenceFormat: 'pdf',
    group: 'regulatory',
    instrument: false,
    requiresPersonalData: true,
    tags: ['data-privacy'],
  },
];

// ---------------------------------------------------------------------------
// PH — Financial / banking
// ---------------------------------------------------------------------------
const PH_FINANCIAL: readonly RequirementDefinition[] = [
  {
    code: 'PH_AFS',
    label: 'Audited Financial Statements (latest 3 years)',
    description: 'Audited Financial Statements for the three most recent fiscal years.',
    whyWeNeedIt: 'Baseline solvency / going-concern check before we engage on any material contract.',
    authority: 'Vendor',
    jurisdictions: ['PH'],
    entityTypes: ['corporation', 'partnership', 'cooperative', 'branch_foreign'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    renewsAfterMonths: 12,
    evidenceFormat: 'pdf',
    group: 'financial',
    instrument: false,
    tags: ['renewable'],
  },
  {
    code: 'PH_BANK_CERT',
    label: 'Bank Account Certification / Cancelled Cheque',
    description:
      'Bank Certification naming the vendor as account holder, or a cancelled cheque for that account.',
    whyWeNeedIt: 'Prevents payment routing errors and confirms the disbursement account is legitimate.',
    authority: 'Insurer / Bank',
    jurisdictions: ['PH', 'US', 'UK', 'EU', 'SG', 'HK', 'OTHER'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    evidenceFormat: 'pdf',
    group: 'financial',
    instrument: false,
  },
  {
    code: 'PH_NON_BANKRUPTCY',
    label: 'Certificate of Non-Bankruptcy / Insolvency',
    description: 'Sworn statement of non-bankruptcy / non-insolvency issued by counsel or notarized.',
    whyWeNeedIt: 'Guardrail before committing to material spend with a vendor.',
    authority: 'Notary / Consular',
    jurisdictions: ['PH'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['medium', 'high'],
    required: false,
    evidenceFormat: 'pdf',
    group: 'financial',
    instrument: false,
    minSpendBand: '1m_10m',
  },
];

// ---------------------------------------------------------------------------
// PH — Governance / sworn declarations / authority
// ---------------------------------------------------------------------------
const PH_GOVERNANCE: readonly RequirementDefinition[] = [
  {
    code: 'PH_OMNIBUS_SWORN',
    label: 'Omnibus Sworn Statement (non-blacklisting)',
    description:
      'Notarized Omnibus Sworn Statement — non-blacklisting, non-conflict, authenticity of documents.',
    whyWeNeedIt:
      'Standard sourcing sworn statement — protects mWell from suppliers on blacklists or with conflicts.',
    authority: 'Notary / Consular',
    jurisdictions: ['PH'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    renewsAfterMonths: 12,
    evidenceFormat: 'pdf',
    group: 'governance',
    instrument: false,
    tags: ['ph-mandatory', 'renewable'],
  },
  {
    code: 'PH_SEC_CERT',
    label: 'Secretary\u2019s Certificate / Board Resolution',
    description:
      'Corporate Secretary\u2019s Certificate or Board Resolution naming the authorized signatory for this engagement.',
    whyWeNeedIt: 'Confirms the person signing our contract has actual authority to bind the vendor.',
    authority: 'Vendor',
    jurisdictions: ['PH'],
    entityTypes: ['corporation', 'partnership', 'cooperative'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    evidenceFormat: 'pdf',
    group: 'governance',
    instrument: false,
  },
  {
    code: 'PH_SPA',
    label: 'Special Power of Attorney (signatory)',
    description: 'Notarized Special Power of Attorney for the vendor\u2019s authorized signatory (if delegated).',
    whyWeNeedIt: 'Alternative to a Sec\u2019s Certificate when authority is delegated by SPA.',
    authority: 'Notary / Consular',
    jurisdictions: ['PH'],
    entityTypes: ['sole_prop', 'partnership', 'branch_foreign'],
    categories: ['*'],
    riskTiers: ['*'],
    required: false,
    evidenceFormat: 'pdf',
    group: 'governance',
    instrument: false,
  },
  {
    code: 'PH_COMPANY_PROFILE',
    label: 'Company Profile, Portfolio and Client References',
    description:
      'Company profile, product or service portfolio, and current / past client references with contact details.',
    whyWeNeedIt:
      'The mWell accreditation form requires a profile and client history so reviewers can validate operating track record and delivered scope.',
    authority: 'Vendor',
    jurisdictions: ['*'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    evidenceFormat: 'any',
    group: 'governance',
    instrument: false,
  },
  {
    code: 'PH_MANPOWER_EXPERIENCE',
    label: 'Manpower, Expertise and Completed Projects',
    description:
      'Headcount by expertise, key qualifications or certifications, and completed projects relevant to the proposed services.',
    whyWeNeedIt:
      'The accreditation form asks service providers to disclose manpower, specialist expertise, and completed projects before mWell awards work.',
    authority: 'Vendor',
    jurisdictions: ['PH'],
    entityTypes: ['*'],
    categories: ['services', 'manpower', 'consulting', 'it_software', 'marketing', 'logistics'],
    riskTiers: ['*'],
    required: true,
    evidenceFormat: 'any',
    group: 'governance',
    instrument: false,
  },
  {
    code: 'PH_GOOD_STANDING_BRANCH',
    label: 'Certificate of Good Standing (branch / parent)',
    description: 'For foreign-registered branches: current Certificate of Good Standing from the home registry.',
    whyWeNeedIt: 'Confirms the foreign parent is not dissolved / in receivership abroad.',
    authority: 'Notary / Consular',
    jurisdictions: ['PH'],
    entityTypes: ['branch_foreign'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    renewsAfterMonths: 12,
    evidenceFormat: 'pdf',
    group: 'governance',
    instrument: false,
  },
];

// ---------------------------------------------------------------------------
// Quality / standards — universal ISO
// ---------------------------------------------------------------------------
const QUALITY: readonly RequirementDefinition[] = [
  {
    code: 'ISO_9001',
    label: 'ISO 9001 Quality Management',
    description: 'ISO 9001:2015 quality management system certificate.',
    whyWeNeedIt: 'Universal baseline QMS signal; requested for master-supply and long-tail vendors.',
    authority: 'ISO',
    jurisdictions: ['*'],
    entityTypes: ['*'],
    categories: ['goods', 'construction', 'manpower', 'services', 'logistics'],
    riskTiers: ['*'],
    required: false,
    renewsAfterMonths: 36,
    evidenceFormat: 'pdf',
    group: 'quality',
    instrument: false,
    tags: ['renewable'],
  },
  {
    code: 'ISO_13485',
    label: 'ISO 13485 Medical Devices QMS',
    description: 'ISO 13485 medical devices quality management system certificate.',
    whyWeNeedIt: 'Required for any medical-device supply chain — FDA also expects it downstream.',
    authority: 'ISO',
    jurisdictions: ['*'],
    entityTypes: ['*'],
    categories: ['medical_pharma'],
    riskTiers: ['*'],
    required: true,
    renewsAfterMonths: 36,
    evidenceFormat: 'pdf',
    group: 'quality',
    instrument: false,
  },
  {
    code: 'ISO_14001',
    label: 'ISO 14001 Environmental',
    description: 'ISO 14001:2015 environmental management system certificate.',
    whyWeNeedIt: 'Signal of environmental governance; required for construction / hazmat categories.',
    authority: 'ISO',
    jurisdictions: ['*'],
    entityTypes: ['*'],
    categories: ['construction', 'logistics'],
    riskTiers: ['medium', 'high'],
    required: false,
    renewsAfterMonths: 36,
    evidenceFormat: 'pdf',
    group: 'quality',
    instrument: false,
  },
  {
    code: 'ISO_27001',
    label: 'ISO 27001 Information Security',
    description: 'ISO/IEC 27001 information security management system certificate.',
    whyWeNeedIt: 'Required for IT / SaaS / data-processor vendors touching mWell systems or data.',
    authority: 'ISO',
    jurisdictions: ['*'],
    entityTypes: ['*'],
    categories: ['it_software', 'consulting', 'subscription'],
    riskTiers: ['*'],
    required: true,
    renewsAfterMonths: 36,
    evidenceFormat: 'pdf',
    group: 'quality',
    instrument: false,
    tags: ['infosec'],
  },
  {
    code: 'CYBERSECURITY_POLICIES',
    label: 'Cybersecurity Policies and Secure SDLC Evidence',
    description:
      'Cybersecurity policy set, access-control standard, incident-response procedure, and secure SDLC or QA security controls.',
    whyWeNeedIt:
      'The accreditation form asks technology providers for cybersecurity policies where applicable; this supports production-readiness review before system access.',
    authority: 'Vendor',
    jurisdictions: ['*'],
    entityTypes: ['*'],
    categories: ['it_software', 'subscription', 'consulting'],
    riskTiers: ['*'],
    required: true,
    evidenceFormat: 'any',
    group: 'quality',
    instrument: false,
    tags: ['infosec'],
  },
];

// ---------------------------------------------------------------------------
// Insurance & bonds — spend-band gated
// ---------------------------------------------------------------------------
const INSURANCE: readonly RequirementDefinition[] = [
  {
    code: 'BOND_PAYMENT',
    label: 'Payment Bond',
    description: 'Surety Payment Bond covering downstream sub-vendor liabilities.',
    whyWeNeedIt: 'Policy \u00a712 protects mWell against a defaulting supplier failing to pay its own vendors.',
    authority: 'Insurer / Bank',
    jurisdictions: ['*'],
    entityTypes: ['*'],
    categories: ['construction', 'goods', 'services'],
    riskTiers: ['*'],
    required: false,
    evidenceFormat: 'pdf',
    group: 'insurance',
    instrument: false,
    minSpendBand: '1m_10m',
    contractTypes: ['project', 'master_supply'],
    tags: ['bond'],
  },
  {
    code: 'BOND_PERFORMANCE',
    label: 'Performance Bond (30%)',
    description: 'Performance Bond equal to 30% of contract value, valid through delivery.',
    whyWeNeedIt: 'Required by mWell Procurement Policy \u00a712 for material projects.',
    authority: 'Insurer / Bank',
    jurisdictions: ['*'],
    entityTypes: ['*'],
    categories: ['construction', 'goods', 'services'],
    riskTiers: ['*'],
    required: false,
    evidenceFormat: 'pdf',
    group: 'insurance',
    instrument: false,
    minSpendBand: '1m_10m',
    contractTypes: ['project', 'master_supply'],
    tags: ['bond'],
  },
  {
    code: 'BOND_WARRANTY',
    label: 'Warranty Bond (10%)',
    description: 'Warranty Bond equal to 10% of contract value, valid for the warranty period.',
    whyWeNeedIt: 'Locks the vendor into after-delivery obligations under \u00a712.',
    authority: 'Insurer / Bank',
    jurisdictions: ['*'],
    entityTypes: ['*'],
    categories: ['construction', 'goods'],
    riskTiers: ['*'],
    required: false,
    evidenceFormat: 'pdf',
    group: 'insurance',
    instrument: false,
    minSpendBand: '1m_10m',
    contractTypes: ['project'],
    tags: ['bond'],
  },
  {
    code: 'BOND_DOWN_PAYMENT',
    label: 'Down-Payment Bond',
    description: 'Bond guaranteeing return of any advance payment / down payment.',
    whyWeNeedIt: 'Where mWell fronts a down payment, this bond is the backstop.',
    authority: 'Insurer / Bank',
    jurisdictions: ['*'],
    entityTypes: ['*'],
    categories: ['construction', 'goods', 'services'],
    riskTiers: ['*'],
    required: false,
    evidenceFormat: 'pdf',
    group: 'insurance',
    instrument: false,
    minSpendBand: '1m_10m',
    tags: ['bond'],
  },
  {
    code: 'BOND_SBLC',
    label: 'Standby Letter of Credit',
    description: 'Standby LC in mWell\u2019s favor issued by a Tier-1 bank.',
    whyWeNeedIt: 'Alternative to bonds for high-value / cross-border engagements.',
    authority: 'Insurer / Bank',
    jurisdictions: ['*'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: false,
    evidenceFormat: 'pdf',
    group: 'insurance',
    instrument: false,
    minSpendBand: '10m_50m',
    tags: ['bond'],
  },
  {
    code: 'INS_CARI',
    label: 'CARI / EARI Insurance',
    description: 'Contractor / Erection All Risk Insurance covering the project period.',
    whyWeNeedIt: 'Required for construction / capex works before mobilization.',
    authority: 'Insurer / Bank',
    jurisdictions: ['*'],
    entityTypes: ['*'],
    categories: ['construction'],
    riskTiers: ['*'],
    required: true,
    renewsAfterMonths: 12,
    evidenceFormat: 'pdf',
    group: 'insurance',
    instrument: false,
    contractTypes: ['project'],
  },
  {
    code: 'INS_TPL',
    label: 'Third-Party Liability Insurance',
    description: 'Third-Party Liability policy with minimum limits set by mWell Risk.',
    whyWeNeedIt: 'Protects mWell, staff, and members of the public from injury / property damage.',
    authority: 'Insurer / Bank',
    jurisdictions: ['*'],
    entityTypes: ['*'],
    categories: ['construction', 'manpower', 'logistics'],
    riskTiers: ['*'],
    required: true,
    renewsAfterMonths: 12,
    evidenceFormat: 'pdf',
    group: 'insurance',
    instrument: false,
  },
  {
    code: 'INS_PROF_INDEMNITY',
    label: 'Professional Indemnity Insurance',
    description: 'Professional Indemnity policy covering advisory and consulting deliverables.',
    whyWeNeedIt: 'Baseline for consulting / advisory engagements that could cause consequential loss.',
    authority: 'Insurer / Bank',
    jurisdictions: ['*'],
    entityTypes: ['*'],
    categories: ['consulting', 'it_software'],
    riskTiers: ['*'],
    required: false,
    renewsAfterMonths: 12,
    evidenceFormat: 'pdf',
    group: 'insurance',
    instrument: false,
    minSpendBand: '100k_1m',
  },
  {
    code: 'INS_WORKMEN',
    label: 'Workmen\u2019s Compensation Cover',
    description: 'Workmen\u2019s Compensation Insurance for all deployed personnel.',
    whyWeNeedIt: 'Legally required for construction and manpower engagements.',
    authority: 'Insurer / Bank',
    jurisdictions: ['*'],
    entityTypes: ['*'],
    categories: ['construction', 'manpower'],
    riskTiers: ['*'],
    required: true,
    renewsAfterMonths: 12,
    evidenceFormat: 'pdf',
    group: 'insurance',
    instrument: false,
    contractTypes: ['manpower_supply', 'project'],
  },
];

// ---------------------------------------------------------------------------
// US — IRS + Secretary of State + DUNS
// ---------------------------------------------------------------------------
const US_ROWS: readonly RequirementDefinition[] = [
  {
    code: 'US_W9',
    label: 'IRS Form W-9',
    description: 'IRS Form W-9 (Request for Taxpayer Identification Number and Certification).',
    whyWeNeedIt: 'Required from any US-based supplier so we can 1099 correctly.',
    authority: 'IRS',
    helpUrl: 'https://www.irs.gov/forms-pubs/about-form-w-9',
    jurisdictions: ['US'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    evidenceFormat: 'pdf',
    group: 'tax',
    instrument: false,
    tags: ['us'],
  },
  {
    code: 'US_W8BENE',
    label: 'IRS Form W-8BEN-E',
    description: 'IRS Form W-8BEN-E (foreign entity beneficial owner) for non-US entities billing a US payer.',
    whyWeNeedIt: 'Treaty-position + withholding certification for non-US vendors invoicing our US entity.',
    authority: 'IRS',
    helpUrl: 'https://www.irs.gov/forms-pubs/about-form-w-8-ben-e',
    jurisdictions: ['UK', 'EU', 'SG', 'HK', 'OTHER'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    evidenceFormat: 'pdf',
    group: 'tax',
    instrument: false,
    tags: ['us-billing'],
  },
  {
    code: 'US_SOS_GOOD_STANDING',
    label: 'Secretary of State Good Standing',
    description: 'Certificate of Good Standing issued by the vendor\u2019s state Secretary of State.',
    whyWeNeedIt: 'Confirms US corporate entity is in good standing in its state of incorporation.',
    authority: 'US_SOS',
    jurisdictions: ['US'],
    entityTypes: ['corporation', 'partnership'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    renewsAfterMonths: 12,
    evidenceFormat: 'pdf',
    group: 'statutory',
    instrument: false,
  },
  {
    code: 'US_EIN',
    label: 'IRS EIN Letter',
    description: 'IRS EIN assignment letter (CP-575 / 147C).',
    whyWeNeedIt: 'Tax ID confirmation independent of W-9 for internal AP setup.',
    authority: 'IRS',
    jurisdictions: ['US'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: false,
    evidenceFormat: 'pdf',
    group: 'tax',
    instrument: false,
  },
  {
    code: 'US_DUNS',
    label: 'DUNS Number',
    description: 'Dun & Bradstreet DUNS number registration confirmation.',
    whyWeNeedIt: 'Common enterprise-vendor identifier; also required by many US-federal aligned programs.',
    authority: 'DUNS',
    jurisdictions: ['US'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: false,
    evidenceFormat: 'pdf',
    group: 'statutory',
    instrument: false,
  },
];

// ---------------------------------------------------------------------------
// EU / UK
// ---------------------------------------------------------------------------
const EU_UK_ROWS: readonly RequirementDefinition[] = [
  {
    code: 'EU_VAT',
    label: 'VAT Registration Certificate',
    description: 'VAT registration certificate issued by the vendor\u2019s home tax authority.',
    whyWeNeedIt: 'Required to correctly handle VAT on cross-border invoices.',
    authority: 'HMRC',
    jurisdictions: ['EU', 'UK'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    renewsAfterMonths: 12,
    evidenceFormat: 'pdf',
    group: 'tax',
    instrument: false,
  },
  {
    code: 'UK_COMPANIES_HOUSE',
    label: 'Companies House Filings',
    description: 'Latest Companies House confirmation statement + certificate of incorporation.',
    whyWeNeedIt: 'UK-registered vendors must be current with Companies House filings.',
    authority: 'Companies House',
    helpUrl: 'https://find-and-update.company-information.service.gov.uk/',
    jurisdictions: ['UK'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    renewsAfterMonths: 12,
    evidenceFormat: 'pdf',
    group: 'statutory',
    instrument: false,
  },
  {
    code: 'UK_PSC',
    label: 'Persons with Significant Control register',
    description: 'PSC (Persons with Significant Control) register from Companies House.',
    whyWeNeedIt: 'Beneficial ownership disclosure — mirrors AMLC obligations we run in PH.',
    authority: 'Companies House',
    jurisdictions: ['UK'],
    entityTypes: ['corporation'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    evidenceFormat: 'pdf',
    group: 'ownership',
    instrument: false,
    tags: ['beneficial-ownership'],
  },
  {
    code: 'EU_GDPR_DPA',
    label: 'GDPR Data Processing Agreement',
    description: 'Signed GDPR-compliant Data Processing Agreement between the vendor and mWell.',
    whyWeNeedIt: 'Required whenever an EU/UK vendor will process personal data of any EU/UK data subject.',
    authority: 'mWell Legal',
    jurisdictions: ['EU', 'UK'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    evidenceFormat: 'signed',
    group: 'legal_instruments',
    instrument: true,
    instrumentCode: 'SIGN_DPA_GDPR',
    templateVersion: 'dpa-gdpr-v1',
    requiresPersonalData: true,
    tags: ['data-privacy'],
  },
  {
    code: 'UK_MODERN_SLAVERY',
    label: 'Modern Slavery Act Statement',
    description: 'Modern Slavery Act (2015) transparency statement, latest year.',
    whyWeNeedIt: 'UK vendors above the £36M revenue threshold must publish this statement.',
    authority: 'HMRC',
    jurisdictions: ['UK'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['medium', 'high'],
    required: false,
    renewsAfterMonths: 12,
    evidenceFormat: 'pdf',
    group: 'governance',
    instrument: false,
  },
];

// ---------------------------------------------------------------------------
// SG / HK
// ---------------------------------------------------------------------------
const APAC_ROWS: readonly RequirementDefinition[] = [
  {
    code: 'SG_ACRA_BIZFILE',
    label: 'ACRA BizFile Business Profile',
    description: 'ACRA (Accounting & Corporate Regulatory Authority) BizFile business profile.',
    whyWeNeedIt: 'Singapore-registered vendors provide this to confirm current standing.',
    authority: 'ACRA',
    helpUrl: 'https://www.bizfile.gov.sg/',
    jurisdictions: ['SG'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    renewsAfterMonths: 12,
    evidenceFormat: 'pdf',
    group: 'statutory',
    instrument: false,
  },
  {
    code: 'HK_BR_CERT',
    label: 'HK Business Registration Certificate',
    description: 'Hong Kong Business Registration Certificate issued by IRD.',
    whyWeNeedIt: 'Mandatory HK regulatory registration; must be current-year.',
    authority: 'HK_CR',
    jurisdictions: ['HK'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    renewsAfterMonths: 12,
    evidenceFormat: 'pdf',
    group: 'statutory',
    instrument: false,
  },
  {
    code: 'HK_CR_FILINGS',
    label: 'HK Companies Registry Filings',
    description: 'Latest Companies Registry annual return / NAR1 filing.',
    whyWeNeedIt: 'Confirms directors and shareholding as filed with the HK Companies Registry.',
    authority: 'HK_CR',
    jurisdictions: ['HK'],
    entityTypes: ['corporation'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    renewsAfterMonths: 12,
    evidenceFormat: 'pdf',
    group: 'statutory',
    instrument: false,
  },
];

// ---------------------------------------------------------------------------
// International generic (jurisdiction-agnostic + fatf risk)
// ---------------------------------------------------------------------------
const INTL_ROWS: readonly RequirementDefinition[] = [
  {
    code: 'INTL_INC_CERT',
    label: 'Country-of-Registration Incorporation Certificate',
    description: 'Certificate of incorporation from the vendor\u2019s primary registry.',
    whyWeNeedIt: 'Base evidence of legal existence for every foreign vendor.',
    authority: 'Notary / Consular',
    jurisdictions: ['US', 'UK', 'EU', 'SG', 'HK', 'OTHER'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    evidenceFormat: 'pdf',
    group: 'statutory',
    instrument: false,
  },
  {
    code: 'INTL_AFS',
    label: 'Audited Financial Statements (USD/EUR)',
    description: 'Audited financials expressed in USD or EUR (or with translation) for the latest 2 years.',
    whyWeNeedIt: 'Comparable solvency check for foreign vendors alongside PH AFS.',
    authority: 'Vendor',
    jurisdictions: ['US', 'UK', 'EU', 'SG', 'HK', 'OTHER'],
    entityTypes: ['corporation', 'partnership'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    renewsAfterMonths: 12,
    evidenceFormat: 'pdf',
    group: 'financial',
    instrument: false,
    tags: ['renewable'],
  },
  {
    code: 'INTL_TAX_RESIDENCY',
    label: 'Certificate of Tax Residency',
    description: 'Certificate of Tax Residency issued by the vendor\u2019s home tax authority.',
    whyWeNeedIt: 'Enables PH-side treaty relief on withholding tax where a treaty exists.',
    authority: 'IRS',
    jurisdictions: ['US', 'UK', 'EU', 'SG', 'HK', 'OTHER'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: false,
    renewsAfterMonths: 12,
    evidenceFormat: 'pdf',
    group: 'tax',
    instrument: false,
  },
  {
    code: 'INTL_APOSTILLE',
    label: 'Apostille / Notarized True Copies',
    description: 'Apostille or notarized certified true copies of foreign registration documents.',
    whyWeNeedIt: 'Required for PH acceptance of foreign-issued corporate documents.',
    authority: 'Notary / Consular',
    jurisdictions: ['US', 'UK', 'EU', 'SG', 'HK', 'OTHER'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    evidenceFormat: 'pdf',
    group: 'governance',
    instrument: false,
  },
  {
    code: 'INTL_EDD',
    label: 'Enhanced Due Diligence Pack',
    description:
      'Enhanced Due Diligence pack (UBO chart, KYC on directors, AML questionnaire) for high-risk jurisdictions.',
    whyWeNeedIt: 'Required when the vendor\u2019s home country appears on the FATF grey / black list.',
    authority: 'Sanctions Body',
    jurisdictions: ['*'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['high'],
    required: true,
    evidenceFormat: 'pdf',
    group: 'ownership',
    instrument: false,
    tags: ['edd'],
  },
  {
    code: 'INTL_SANCTIONS_DECL',
    label: 'Sanctions Screening Declaration',
    description:
      'Signed declaration confirming clearance against OFAC / EU / UN sanctions lists.',
    whyWeNeedIt: 'Attestable proof that the vendor and its UBOs are not sanctioned.',
    authority: 'Sanctions Body',
    jurisdictions: ['*'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    evidenceFormat: 'signed',
    group: 'legal_instruments',
    instrument: true,
    instrumentCode: 'SIGN_PEP_SANCTIONS',
    templateVersion: 'pep-sanctions-v1',
    tags: ['sanctions'],
  },
  {
    code: 'INTL_ABAC_CERT',
    label: 'Anti-Bribery & Anti-Corruption Certification',
    description: 'ABAC certification aligned with UK Bribery Act (2010) / FCPA (US).',
    whyWeNeedIt: 'Baseline attestation for any international engagement.',
    authority: 'Vendor',
    jurisdictions: ['US', 'UK', 'EU', 'SG', 'HK', 'OTHER'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: false,
    evidenceFormat: 'pdf',
    group: 'governance',
    instrument: false,
  },
];

// ---------------------------------------------------------------------------
// Beneficial ownership — jurisdiction-agnostic (PH SEC MC 28 + AMLC)
// ---------------------------------------------------------------------------
const OWNERSHIP_ROWS: readonly RequirementDefinition[] = [
  {
    code: 'PH_UBO_DISCLOSURE',
    label: 'Beneficial Ownership Disclosure (SEC MC 28)',
    description:
      'Beneficial Ownership Disclosure aligned with SEC Memorandum Circular 28-2020 / AMLC guidelines.',
    whyWeNeedIt:
      'AML/CFT compliance and to comply with SEC MC 28 obligations for the ultimate beneficial owners.',
    authority: 'SEC',
    jurisdictions: ['PH'],
    entityTypes: ['corporation', 'partnership', 'branch_foreign'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    renewsAfterMonths: 12,
    evidenceFormat: 'pdf',
    group: 'ownership',
    instrument: false,
    tags: ['beneficial-ownership', 'renewable'],
  },
  {
    code: 'INTL_UBO_CHART',
    label: 'Ultimate Beneficial Owner (UBO) Chart',
    description: 'UBO ownership chart down to natural persons with 25%+ ownership.',
    whyWeNeedIt: 'Global AML best practice — mirrors PH SEC MC 28 for jurisdictions without a public UBO register.',
    authority: 'Vendor',
    jurisdictions: ['US', 'EU', 'SG', 'HK', 'OTHER'],
    entityTypes: ['corporation', 'partnership', 'branch_foreign'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    evidenceFormat: 'pdf',
    group: 'ownership',
    instrument: false,
    tags: ['beneficial-ownership'],
  },
];

// ---------------------------------------------------------------------------
// Legal instruments — sign-in-browser via SignaturePad
// ---------------------------------------------------------------------------
const INSTRUMENT_ROWS: readonly RequirementDefinition[] = [
  {
    code: 'SIGN_NDA',
    label: 'Mutual Non-Disclosure Agreement',
    description:
      'Standard mutual NDA. Signable in-browser; countersigned by mWell Legal on approval.',
    whyWeNeedIt: 'Protects commercial + technical information exchanged during evaluation and delivery.',
    authority: 'mWell Legal',
    jurisdictions: ['*'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    evidenceFormat: 'signed',
    group: 'legal_instruments',
    instrument: true,
    instrumentCode: 'SIGN_NDA',
    templateVersion: '2026.07.10',
  },
  {
    code: 'SIGN_DPA_PH',
    label: 'Data Sharing / Processing Agreement (PH)',
    description: 'NPC-aligned Data Sharing / Processing Agreement (Republic Act 10173).',
    whyWeNeedIt: 'Legally required to process personal data of PH data subjects.',
    authority: 'mWell Legal',
    jurisdictions: ['PH'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    evidenceFormat: 'signed',
    group: 'legal_instruments',
    instrument: true,
    instrumentCode: 'SIGN_DPA_PH',
    templateVersion: 'dpa-ph-v1',
    requiresPersonalData: true,
    tags: ['data-privacy'],
  },
  {
    code: 'SIGN_CODE_ETHICS',
    label: 'Supplier Code of Ethics acknowledgement',
    description: 'Acknowledgement of the mWell Supplier Code of Ethics / Conduct.',
    whyWeNeedIt: 'Codifies conduct expectations (labor, environment, integrity) with every supplier.',
    authority: 'mWell Legal',
    jurisdictions: ['*'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    evidenceFormat: 'signed',
    group: 'legal_instruments',
    instrument: true,
    instrumentCode: 'SIGN_CODE_ETHICS',
    templateVersion: 'coc-v1',
  },
  {
    code: 'SIGN_ABAC_DECL',
    label: 'Anti-Bribery & Anti-Corruption declaration',
    description: 'Signed ABAC declaration aligned with UK Bribery Act / FCPA / RA 3019.',
    whyWeNeedIt: 'Vendor-side attestation of ABAC compliance — required across every engagement.',
    authority: 'mWell Legal',
    jurisdictions: ['*'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    evidenceFormat: 'signed',
    group: 'legal_instruments',
    instrument: true,
    instrumentCode: 'SIGN_ABAC_DECL',
    templateVersion: 'abac-v1',
  },
  {
    code: 'SIGN_COI',
    label: 'Conflict-of-Interest declaration',
    description: 'Signed Conflict-of-Interest declaration with disclosure fields.',
    whyWeNeedIt: 'Flags any related-party relationship with mWell employees or officers.',
    authority: 'mWell Legal',
    jurisdictions: ['*'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    evidenceFormat: 'signed',
    group: 'legal_instruments',
    instrument: true,
    instrumentCode: 'SIGN_COI',
    templateVersion: 'coi-v1',
  },
  {
    code: 'SIGN_MSA',
    label: 'Master Service Agreement (countersign)',
    description: 'Countersigned Master Service Agreement / Master Supply Agreement.',
    whyWeNeedIt: 'Governs the umbrella commercial terms for recurring or master-supply engagements.',
    authority: 'mWell Legal',
    jurisdictions: ['*'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: false,
    evidenceFormat: 'signed',
    group: 'legal_instruments',
    instrument: true,
    instrumentCode: 'SIGN_MSA',
    templateVersion: 'msa-v1',
    contractTypes: ['master_supply', 'sla', 'retainer', 'project'],
  },
  {
    code: 'SIGN_NO_LITIGATION',
    label: 'Statement of No Pending Litigation',
    description:
      'Signed statement that no material litigation or regulatory action is pending against the vendor or its officers.',
    whyWeNeedIt: 'Diligence data point; forces disclosure of anything that could affect performance.',
    authority: 'mWell Legal',
    jurisdictions: ['*'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: true,
    evidenceFormat: 'signed',
    group: 'legal_instruments',
    instrument: true,
    instrumentCode: 'SIGN_NO_LITIGATION',
    templateVersion: 'no-litigation-v1',
  },
  {
    code: 'SIGN_WHISTLEBLOWER',
    label: 'Whistleblower Policy acknowledgement',
    description: 'Acknowledgement that vendor personnel understand mWell\u2019s whistleblower policy.',
    whyWeNeedIt: 'Signals to vendor staff that they can report unethical behavior without retaliation.',
    authority: 'mWell Legal',
    jurisdictions: ['*'],
    entityTypes: ['*'],
    categories: ['*'],
    riskTiers: ['*'],
    required: false,
    evidenceFormat: 'signed',
    group: 'legal_instruments',
    instrument: true,
    instrumentCode: 'SIGN_WHISTLEBLOWER',
    templateVersion: 'whistleblower-v1',
  },
];

// ---------------------------------------------------------------------------
// Aggregate export
// ---------------------------------------------------------------------------
export const REQUIREMENT_CATALOG: readonly RequirementDefinition[] = Object.freeze([
  ...PH_STATUTORY,
  ...PH_TAX,
  ...PH_REGULATORY,
  ...PH_FINANCIAL,
  ...PH_GOVERNANCE,
  ...QUALITY,
  ...INSURANCE,
  ...US_ROWS,
  ...EU_UK_ROWS,
  ...APAC_ROWS,
  ...INTL_ROWS,
  ...OWNERSHIP_ROWS,
  ...INSTRUMENT_ROWS,
] as readonly RequirementDefinition[]);

/** O(1) lookup by catalog code. */
export const CATALOG_BY_CODE: Readonly<Record<string, RequirementDefinition>> =
  Object.freeze(
    REQUIREMENT_CATALOG.reduce<Record<string, RequirementDefinition>>((acc, def) => {
      acc[def.code] = def;
      return acc;
    }, {}),
  );

/** All instrument-only catalog codes. */
export const INSTRUMENT_CODES: readonly InstrumentCode[] = REQUIREMENT_CATALOG
  .filter((d): d is RequirementDefinition & { instrumentCode: InstrumentCode } =>
    Boolean(d.instrument && d.instrumentCode),
  )
  .map((d) => d.instrumentCode);

/** Total catalog size — exported so tests can pin the invariant. */
export const CATALOG_SIZE = REQUIREMENT_CATALOG.length;

/** Sanity re-export — the type + convenience helpers. */
export type { RequirementDefinition, SpendBand };
