-- Make Event reconciliation the immutable canonical key for its generated
-- Finance close entry, regardless of editable reference or period fields.

do $$
begin
  if exists (
    select 1
    from core.finance_close_entries close_entry
    where close_entry.source_record_type = 'event_reconciliation'
    group by close_entry.source_record_id
    having count(*) > 1
  ) then
    raise exception 'Duplicate Event reconciliation Finance close entries must be resolved before applying canonical uniqueness';
  end if;
end;
$$;

create unique index if not exists finance_close_event_reconciliation_source_uidx
on core.finance_close_entries(source_record_id)
where source_record_type = 'event_reconciliation';

alter function core.manage_finance_close_entry(jsonb)
  rename to manage_finance_close_entry_pre_event_settlement_controls;

create or replace function core.manage_finance_close_entry(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_action text := payload->>'action';
  v_entry core.finance_close_entries;
  v_source_id text;
begin
  if auth.uid() is null then
    raise exception 'Authenticated Finance actor required';
  end if;
  if not core.has_live_cap('warehouse', 'manage_finance_close') then
    raise exception 'Not authorized: warehouse.manage_finance_close';
  end if;

  if v_action = 'save'
     and payload->>'source_record_type' = 'event_reconciliation' then
    v_source_id := nullif(pg_catalog.btrim(payload->>'source_record_id'), '');
    if v_source_id is null then
      raise exception 'Event reconciliation source ID is required';
    end if;
    if exists (
      select 1
      from warehouse.event_settlements settlement
      where settlement.reconciliation_event_id = v_source_id
         or settlement.event_id = v_source_id
    ) then
      raise exception 'The Finance close entry is generated by Event settlement approval and cannot be prepared manually';
    end if;
  elsif v_action <> 'save' then
    select *
    into v_entry
    from core.finance_close_entries close_entry
    where close_entry.id = nullif(payload->>'id', '')::uuid
    for update;
    if not found then
      raise exception 'Finance close entry not found';
    end if;
    if v_entry.source_record_type = 'event_reconciliation'
       and v_action in ('post', 'reconcile') then
      perform private.assert_finance_close_binding(
        v_entry.source_record_type,
        v_entry.source_record_id,
        v_entry.evidence_record_type,
        v_entry.evidence_record_id
      );
    end if;
  end if;

  return core.manage_finance_close_entry_pre_event_settlement_controls(payload);
end;
$$;

revoke all on function
  core.manage_finance_close_entry_pre_event_settlement_controls(jsonb)
from public, anon, authenticated;
grant execute on function
  core.manage_finance_close_entry_pre_event_settlement_controls(jsonb)
to service_role;

revoke all on function core.manage_finance_close_entry(jsonb)
from public, anon;
grant execute on function core.manage_finance_close_entry(jsonb)
to authenticated, service_role;

select pg_notify('pgrst', 'reload schema');
